"use client";

import { motion, AnimatePresence } from "framer-motion";

interface Props {
  visible: boolean;
}

const FILES = [
  { name: "HeroSection.tsx", type: "component" },
  { name: "FeaturesGrid.tsx", type: "component" },
  { name: "PricingTable.tsx", type: "component" },
  { name: "CTASection.tsx", type: "component" },
  { name: "Footer.tsx", type: "component" },
  { name: "page.tsx", type: "page" },
];

const RAW_CODE = `// HeroSection.tsx — generated by Eggthropic Execution Lab
export function HeroSection() {
  return (
    <section className="relative min-h-screen flex items-center">
      <div className="max-w-6xl mx-auto px-8">
        <h1 className="text-6xl font-bold gradient-text">
          Ship faster with Stackr
        </h1>
        <p className="text-xl text-slate-400 mt-6 max-w-2xl">
          The CLI that turns your TypeScript into living API docs.
        </p>
        <div className="flex gap-4 mt-10">
          <Button variant="primary">Get started free</Button>
          <Button variant="ghost">View docs</Button>
        </div>
      </div>
    </section>
  );
}`;

function colorizeCode(raw: string): string {
  let s = raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Comments
  s = s.replace(/(\/\/.+)/g, '<span class="text-slate-500">$1</span>');

  // Keywords
  s = s.replace(
    /\b(export|function|return|const|let|var|import|from|default)\b/g,
    '<span class="text-violet-400">$1</span>'
  );

  // JSX tags (after html-escaping)
  s = s.replace(
    /(&lt;\/?)([\w]+)/g,
    '$1<span class="text-sky-400">$2</span>'
  );

  // className values (content inside className="...")
  s = s.replace(
    /(className=&quot;)([^&]+)(&quot;)/g,
    '$1<span class="text-amber-400">$2</span>$3'
  );
  s = s.replace(
    /(className=")([^"]+)(")/g,
    '$1<span class="text-amber-400">$2</span>$3'
  );

  // Strings in quotes (not already colored)
  s = s.replace(
    /(?<![>=])"([^"<>]+)"/g,
    '<span class="text-emerald-400">"$1"</span>'
  );

  return s;
}

export default function ResultPreview({ visible }: Props) {
  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 8 }}
          transition={{ duration: 0.5, ease: "easeOut" }}
          className="glass rounded-2xl overflow-hidden mt-4"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-5 py-3 border-b border-white/8 bg-white/[0.02]">
            <span className="font-mono text-[10px] tracking-widest text-slate-500 uppercase">
              Generated Output
            </span>
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-emerald-400/10 border border-emerald-400/20 text-emerald-400 text-[10px] font-mono">
              ✓ Complete
            </span>
          </div>

          <div className="p-5 flex flex-col lg:flex-row gap-6">
            {/* Left: file list + metrics */}
            <div className="lg:w-64 shrink-0">
              {/* Metrics */}
              <div className="flex flex-wrap gap-2 mb-4">
                {[
                  { label: "Files", value: "6" },
                  { label: "Lines", value: "847" },
                  { label: "Elapsed", value: "~7s" },
                ].map((m) => (
                  <div
                    key={m.label}
                    className="glass rounded-lg px-2.5 py-1.5 flex items-baseline gap-1.5"
                  >
                    <span className="font-mono text-[10px] text-slate-500 uppercase tracking-wide">
                      {m.label}:
                    </span>
                    <span className="font-mono text-xs text-white">{m.value}</span>
                  </div>
                ))}
              </div>

              {/* File list */}
              <div className="glass rounded-xl overflow-hidden">
                <div className="px-3 py-2 border-b border-white/8">
                  <span className="font-mono text-[10px] tracking-widest text-slate-500 uppercase">
                    Files
                  </span>
                </div>
                <div className="divide-y divide-white/5">
                  {FILES.map((f) => (
                    <div
                      key={f.name}
                      className="flex items-center justify-between px-3 py-2"
                    >
                      <div className="flex items-center gap-2 min-w-0">
                        <span className="font-mono text-[11px] text-slate-300 truncate">
                          {f.name}
                        </span>
                      </div>
                      <div className="flex items-center gap-2 shrink-0 ml-2">
                        <span className="font-mono text-[9px] text-slate-600 uppercase">
                          {f.type}
                        </span>
                        <span className="text-emerald-400 text-[10px]">✓</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Right: code preview */}
            <div className="flex-1 min-w-0">
              <div className="rounded-xl overflow-hidden border border-white/8">
                <div className="flex items-center justify-between px-3 py-2 bg-white/[0.03] border-b border-white/8">
                  <span className="font-mono text-[10px] text-slate-500">HeroSection.tsx</span>
                  <span className="font-mono text-[9px] text-slate-600 uppercase tracking-wide">tsx</span>
                </div>
                <div
                  className="p-4 font-mono text-[11px] leading-relaxed overflow-x-auto whitespace-pre"
                  style={{ background: "#060a11" }}
                  dangerouslySetInnerHTML={{ __html: colorizeCode(RAW_CODE) }}
                />
              </div>
            </div>
          </div>

          <div className="px-5 pb-4">
            <p className="text-[10px] text-slate-600">
              This output is illustrative. Generated by Eggthropic Execution Lab — not an official Anthropic interface.
            </p>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
